name: i501
dependencies:
  - python=3.10
  - pip
  - pip:
    - ipykernel
    - dash
    - pandas
    - matplotlib
    - seaborn
    - lxml
    - requests
    - python-dotenv
    - tqdm
    - psutil
    - nltk
    - termcolor
    - scikit-learn